# Generated by Django 3.0.8 on 2022-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.TextField(null=True)),
                ('user', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'CustomPrayers',
            },
        ),
    ]
