# Generated by Django 3.0.8 on 2022-06-27 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrayers',
            fields=[
                ('prayer', models.TextField(max_length=1250, null=True)),
                ('requested_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('request_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'CustomPrayers',
            },
        ),
    ]
