# Generated by Django 3.0.8 on 2022-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(max_length=200)),
                ('prayer_album', models.CharField(max_length=200)),
                ('prayer_language', models.CharField(choices=[('English', 'English')], default='English', max_length=20)),
                ('prayer_img', models.FileField(blank=True, upload_to='')),
                ('year', models.IntegerField(blank=True)),
                ('song_file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'PrayersRequested',
            },
        ),
    ]
