# Generated by Django 3.0.8 on 2022-09-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_prayerrequested'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequested',
            name='user',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
