# Generated by Django 3.0.8 on 2022-09-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0006_prayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayers',
            name='request_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='prayers',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
