# Generated by Django 3.0.8 on 2022-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_auto_20220912_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('English', 'English')], default='Hindi', max_length=20),
        ),
    ]
